name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Merge CI requirements
        run: |
          bash scripts/ci_merge_requirements.sh || true

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          # Ensure essential test deps
          pip install pytest Unidecode flake8

      - name: Show env
        run: |
          python --version
          pip --version

      - name: Lint
        run: |
          flake8 scripts || true

      - name: Tests (quick, stable set)
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests/test_classify_v2.py tests/test_unify.py

      - name: Verify Phase 1
        run: |
          bash scripts/verify_phase1.sh
