name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Merge CI requirements
        run: |
          bash scripts/ci_merge_requirements.sh

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show env
        run: |
          python --version
          pip --version
          python -c "import sys,site;print(sys.executable);print('\n'.join(site.getsitepackages()))"

      - name: Lint
        run: |
          flake8 scripts || true

      - name: Tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q || (echo 'pytest failed with exit code $?' && exit 1)

      - name: Verify Phase 1
        run: |
          bash scripts/verify_phase1.sh
