name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 scripts || true
      - name: Tests
        env:
          PYTHONPATH: .
        run: |
          pytest -q
      - name: Verify Phase 1
        run: |
          bash scripts/verify_phase1.sh
