name: CI
on: [push, pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify Scripts
        run: |
          bash scripts/verify_repo_state.sh
          bash scripts/verify_publish.sh
          bash scripts/verify_phase6_gui.sh
