name: Launcher Verification
on:
  push:
    paths:
      - "scripts/launchers/launcher.sh"
      - "scripts/verify_venv_launcher.sh"
      - "scripts/python/gui_backend.py"
  pull_request:
    paths:
      - "scripts/launchers/launcher.sh"
      - "scripts/verify_venv_launcher.sh"
      - "scripts/python/gui_backend.py"
  workflow_dispatch:

jobs:
  verify-launcher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Bootstrap venv (idempotent)
        run: |
          python -m venv .venv || true
          .venv/bin/python -m pip install -U pip || true
      - name: Verify venv launcher
        run: bash scripts/verify_venv_launcher.sh
