name: Phase 7 Verify
on:
  push:
    branches: [ main, my-barcode-datacenter, 'codex/**' ]
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python - <<'PY'
import sys, subprocess
subprocess.check_call([sys.executable, "-m", "pip", "install", "PySimpleGUI"])
PY
      - name: Verify Phase 7
        run: bash scripts/verify_phase7_status.sh
