name: README Verification
on:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"
  workflow_dispatch:

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Basic README checks
        run: |
          test -s README.md
          grep -q "Smart-Mode" README.md
